"use client";

import { useEffect, useMemo, useState } from "react";
import {
  MagnifyingGlass,
  Funnel,
  Plus,
  PencilSimple,
  Trash,
  Eye,
  EyeSlash,
  LightbulbFilament,
  House,
  Users,
  FileText,
  ChartBar,
  UserPlus,
  Student,
  Handshake,
  Folder,
  Calendar,
  Headset,
  CaretUp,
  CaretDown,
} from "@phosphor-icons/react";
import { InputGroup } from "@components/ui/InputGroup";
import { Badge } from "@components/ui/Badge";
import { Pagination } from "@components/ui/pagination";
import { Table } from "@components/layout/table";
import { Sidebar } from "@components/layout/sidebar";
import { SidebarTab } from "@components/ui/sidebar-tab";
import { cn } from "@components/utils/cn";
import { MemberFormDialog } from "./member-form-dialog";
import type { MemberFormData } from "./member-form-dialog";
import { DeleteDialog } from "./delete-dialog";
import {
  INITIAL_MEMBERS,
  INITIAL_SUGGESTIONS,
  type Member,
  type MemberRole,
  type ViewerRole,
} from "./roles-data";

const PAGE_SIZE = 8;
const COLUMNS = ["ID", "Name & Surname", "Roles", "Gmail", "Password", "Notes", "Created", "Actions"] as const;
const COLUMN_COUNT = COLUMNS.length;

function formatDate(value: string) {
  const date = new Date(value);
  return {
    date: new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(date),
    time: new Intl.DateTimeFormat("en-US", { hour: "numeric", minute: "2-digit", hour12: true }).format(date),
  };
}

function maskValue(value: string): string {
  return "\u2022".repeat(8);
}

function maskGoogle(email: string): string {
  const parts = email.split("@");
  if (parts.length !== 2) return maskValue(email);
  return "\u2022".repeat(8) + "@" + parts[1];
}

// ─── Main Page ─────────────────────────────────────────────

export default function RolesPage() {
  // ── Mock RBAC role (toggle to test Moderator vs Owner/Admin) ──
  const [currentUserRole, setCurrentUserRole] = useState<ViewerRole>("Owner");

  const [members, setMembers] = useState<Member[]>(INITIAL_MEMBERS);
  const [query, setQuery] = useState("");
  const [page, setPage] = useState(1);
  const [activeTab, setActiveTab] = useState<"members" | "suggestions">("members");

  // Visibility toggles per-member for sensitive fields
  const [visibleEmails, setVisibleEmails] = useState<Set<string>>(new Set());
  const [visiblePasswords, setVisiblePasswords] = useState<Set<string>>(new Set());

  // Dialog states
  const [formOpen, setFormOpen] = useState(false);
  const [editingMember, setEditingMember] = useState<Member | null>(null);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [deletingMember, setDeletingMember] = useState<Member | null>(null);

  const isPrivileged = currentUserRole === "Owner" || currentUserRole === "Admin";
  const suggestionCount = INITIAL_SUGGESTIONS.filter(
    (s) => s.status === "New" || s.status === "In Review",
  ).length;

  // ── Filtering ──
  const filteredMembers = useMemo(() => {
    const lowered = query.trim().toLowerCase();
    return members.filter((member) => {
      if (lowered === "") return true;
      return (
        member.id.toLowerCase().includes(lowered) ||
        member.name.toLowerCase().includes(lowered) ||
        member.gmail.toLowerCase().includes(lowered)
      );
    });
  }, [members, query]);

  const totalPages = Math.max(1, Math.ceil(filteredMembers.length / PAGE_SIZE));

  useEffect(() => {
    setPage(1);
  }, [query]);

  useEffect(() => {
    setPage((prev) => Math.min(prev, totalPages));
  }, [totalPages]);

  const pagedMembers = filteredMembers.slice(
    (page - 1) * PAGE_SIZE,
    page * PAGE_SIZE,
  );

  // ── Handlers ──
  const toggleEmailVisibility = (id: string) => {
    setVisibleEmails((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const togglePasswordVisibility = (id: string) => {
    setVisiblePasswords((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const handleAddMember = () => {
    setEditingMember(null);
    setFormOpen(true);
  };

  const handleEditMember = (member: Member) => {
    setEditingMember(member);
    setFormOpen(true);
  };

  const handleDeleteMember = (member: Member) => {
    setDeletingMember(member);
    setDeleteOpen(true);
  };

  const handleSaveForm = (data: MemberFormData) => {
    if (editingMember) {
      setMembers((prev) =>
        prev.map((m) =>
          m.id === editingMember.id
            ? { ...m, ...data, passwordAutoGenerated: false }
            : m,
        ),
      );
    } else {
      const newMember: Member = {
        id: `M-${String(members.length + 1).padStart(3, "0")}`,
        ...data,
        createdAt: new Date().toISOString(),
        department: data.department,
        passwordAutoGenerated: true,
      };
      setMembers((prev) => [...prev, newMember]);
    }
  };

  const handleConfirmDelete = () => {
    if (!deletingMember) return;
    setMembers((prev) => prev.filter((m) => m.id !== deletingMember.id));
    setDeletingMember(null);
  };

  // ── Button styles (shared) ──
  const iconBtnClasses =
    "inline-flex h-8 w-8 items-center justify-center rounded-lg text-(--text-muted) transition-[color,background-color,transform] duration-150 hover:duration-0 ease-out hover:bg-(--bg-subtle) hover:text-(--text-primary) active:scale-[0.97] focus-visible:shadow-[0_0_0_4px_var(--focus-ring)] focus-visible:outline-none motion-reduce:transition-none motion-reduce:active:scale-100";

  return (
    <div className="flex min-h-screen bg-(--bg-subtle)">
      {/* ── Sidebar ── */}
      <div className="flex border-r border-(--border-subtle-plus) flex-shrink-0">
        <Sidebar defaultCollapsed={false}>
          <Sidebar.Content>
            <Sidebar.Header />
            <Sidebar.Nav>
              <SidebarTab
                icon={<House size={16} weight="bold" />}
                label="Home"
                active={false}
              />
              <SidebarTab
                icon={<LightbulbFilament size={16} weight="bold" />}
                label="Suggestions"
                active={false}
              />
              <SidebarTab
                icon={<FileText size={16} weight="bold" />}
                label="Logs"
                active={false}
              />
              <SidebarTab
                icon={<ChartBar size={16} weight="bold" />}
                label="Analytics"
                active={false}
              />
              <SidebarTab
                icon={<Users size={16} weight="bold" />}
                label="Roles"
                active={true}
              />
              <SidebarTab
                icon={<UserPlus size={16} weight="bold" />}
                label="Recruitment"
                active={false}
              />
              <SidebarTab
                icon={<Student size={16} weight="bold" />}
                label="Student Associations"
                active={false}
              />
              <SidebarTab
                icon={<Handshake size={16} weight="bold" />}
                label="Partners"
                active={false}
              />
              <SidebarTab
                icon={<Folder size={16} weight="bold" />}
                label="Documents"
                active={false}
              />
              <SidebarTab
                icon={<Calendar size={16} weight="bold" />}
                label="Content Plan"
                active={false}
              />
              <SidebarTab
                icon={<Headset size={16} weight="bold" />}
                label="Support"
                active={false}
              />
            </Sidebar.Nav>
          </Sidebar.Content>
          <Sidebar.Footer userName="Paul Nekrasov" userRole={currentUserRole} />
        </Sidebar>
      </div>

      {/* ── Main Content ── */}
      <div className="flex min-w-0 flex-1 flex-col">
        {/* ── Header ── */}
        <header className="border-b border-(--border-subtle-plus) bg-(--bg-subtle) px-6 py-8">
          <div className="mx-auto w-full max-w-[1440px]">
            <div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <nav className="mb-2 flex items-center gap-2 text-xs font-medium text-(--text-muted)">
                  <span>Admin</span>
                  <span className="opacity-40">/</span>
                  <span className="text-(--text-primary)">Roles</span>
                </nav>
                <div className="flex items-center gap-3">
                  <h1 className="text-2xl font-bold tracking-tight text-(--text-primary)">Roles</h1>
                  <Badge variant="gray" className="rounded-full bg-(--bg-subtle-plus) px-2 py-0.5 text-[10px] font-bold">
                    {filteredMembers.length}
                  </Badge>
                </div>
              </div>

              {/* ── RBAC Role Switcher (dev tool) ── */}
              <div className="flex flex-col items-end gap-2">
                <span className="text-[10px] font-bold uppercase tracking-widest text-(--text-subtle)">
                  Viewing as:
                </span>
                <div className="flex items-center gap-1 rounded-lg border border-(--border-subtle) bg-(--bg-base) p-1 shadow-sm">
                  {(["Owner", "Admin", "Moderator"] as const).map((role) => (
                    <button
                      key={role}
                      type="button"
                      onClick={() => setCurrentUserRole(role)}
                      className={cn(
                        "rounded-md px-3 py-1 text-xs font-semibold transition-all duration-150 active:scale-[0.97]",
                        currentUserRole === role
                          ? "bg-(--color-brand) text-(--text-on-accent) shadow-md"
                          : "text-(--text-muted) hover:bg-(--bg-subtle) hover:text-(--text-primary)",
                      )}
                    >
                      {role}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </header>

        <main id="main-content" className="flex-1 overflow-x-hidden bg-(--bg-base) p-6">
          <div className="mx-auto w-full max-w-[1440px] space-y-6">
            {/* ── Tabs & Action Bar Header ── */}
            <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              {/* ── Tabs ── */}
              <div className="flex items-center gap-1 rounded-lg border border-(--border-subtle-plus) bg-(--bg-base) p-1 w-fit">
                <button
                  type="button"
                  onClick={() => setActiveTab("members")}
                  className={cn(
                    "inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-sm font-medium transition-[color,background-color,transform] duration-150 hover:duration-0 ease-out active:scale-[0.97] motion-reduce:active:scale-100",
                    activeTab === "members"
                      ? "bg-(--bg-base) text-(--text-primary) shadow-[var(--shadow-subtle)]"
                      : "text-(--text-muted) hover:text-(--text-primary) hover:bg-(--bg-subtle)",
                  )}
                >
                  <Users size={16} weight="bold" aria-hidden="true" />
                  Members
                </button>
                {isPrivileged && (
                  <button
                    type="button"
                    onClick={() => setActiveTab("suggestions")}
                    className={cn(
                      "inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-sm font-medium transition-[color,background-color,transform] duration-150 hover:duration-0 ease-out active:scale-[0.97] motion-reduce:active:scale-100",
                      activeTab === "suggestions"
                        ? "bg-(--bg-base) text-(--text-primary) shadow-[var(--shadow-subtle)]"
                        : "text-(--text-muted) hover:text-(--text-primary) hover:bg-(--bg-subtle)",
                    )}
                  >
                    <LightbulbFilament size={16} weight="bold" aria-hidden="true" />
                    Suggestions
                    {suggestionCount > 0 && (
                      <Badge variant="destructive" size="sm" className="ml-1 h-5 px-1.5 text-[10px]">
                        {suggestionCount}
                      </Badge>
                    )}
                  </button>
                )}
              </div>

              {/* ── Action Bar ── */}
              {activeTab === "members" && (
                <div className="flex flex-wrap items-center gap-3">
                  <div className="relative flex min-w-[320px] max-w-md items-center h-10">
                    <div className="absolute left-3.5 z-10 pointer-events-none opacity-50">
                      <MagnifyingGlass size={16} weight="bold" />
                    </div>
                    <input
                      id="member-search"
                      type="search"
                      value={query}
                      onChange={(e) => setQuery(e.target.value)}
                      placeholder="Search by name, ID, or email..."
                      autoComplete="off"
                      className="h-full w-full rounded-lg border border-(--border-subtle) bg-(--bg-base) pl-10 pr-4 text-sm font-medium text-(--text-primary) placeholder:text-(--text-muted) focus:border-(--color-brand) focus:outline-none focus:ring-4 focus:ring-(--focus-ring) transition-all"
                    />
                  </div>

                  {/* Filter */}
                  <button
                    type="button"
                    className="inline-flex h-10 items-center gap-2 rounded-lg border border-(--border-subtle) bg-(--bg-base) px-3 py-2 text-sm font-semibold text-(--text-muted) transition-all hover:bg-(--bg-subtle) hover:text-(--text-primary) active:scale-[0.97]"
                  >
                    <Funnel size={16} weight="bold" aria-hidden="true" />
                    <span>Filter</span>
                    <CaretDown size={12} weight="bold" className="opacity-40" />
                  </button>

                  <div className="hidden flex-1 sm:block" />

                  {/* Add / Suggest Member */}
                  {isPrivileged ? (
                    <button
                      type="button"
                      onClick={handleAddMember}
                      className="inline-flex h-10 items-center gap-2 rounded-lg bg-(--color-brand) px-4 py-2 text-sm font-bold text-(--text-on-accent) shadow-lg shadow-(--color-brand)/20 transition-all hover:translate-y-[-1px] active:scale-[0.97]"
                    >
                      <Plus size={16} weight="bold" aria-hidden="true" />
                      Add member
                    </button>
                  ) : (
                    <button
                      type="button"
                      className="inline-flex h-10 items-center gap-2 rounded-lg bg-amber-500 px-4 py-2 text-sm font-bold text-white shadow-lg shadow-amber-500/20 transition-all hover:translate-y-[-1px] active:scale-[0.97]"
                    >
                      <LightbulbFilament size={16} weight="bold" aria-hidden="true" />
                      Suggest member
                    </button>
                  )}
                </div>
              )}
            </div>

            {activeTab === "members" ? (
              <>
                {/* ── Members Table ── */}
                <div className="overflow-hidden rounded-xl border border-(--border-subtle-plus) bg-(--bg-base) shadow-[var(--shadow-subtle)]">
                  <Table>
                    <Table.Header>
                      <Table.Row className="bg-(--bg-subtle)/60 hover:bg-(--bg-subtle)/60 hover:shadow-none">
                        {COLUMNS.map((col) => (
                          <Table.Head
                            key={col}
                            className="select-none text-[11px] font-semibold uppercase tracking-wider text-(--text-muted)"
                          >
                            <div className={cn("flex items-center gap-2", col === "Actions" && "justify-end pr-6")}>
                              {col}
                              {col !== "Actions" && (
                                <div className="flex flex-col opacity-30">
                                  <CaretUp size={8} weight="bold" />
                                  <CaretDown size={8} weight="bold" className="-mt-0.5" />
                                </div>
                              )}
                            </div>
                          </Table.Head>
                        ))}
                      </Table.Row>
                    </Table.Header>

                    <Table.Body>
                      {pagedMembers.length > 0 ? (
                        pagedMembers.map((member) => {
                          const emailVisible = visibleEmails.has(member.id);
                          const passwordVisible = visiblePasswords.has(member.id);
                          const canShowPassword = !!member.passwordAutoGenerated;

                          return (
                            <Table.Row key={member.id}>
                              {/* ID */}
                              <Table.Cell className="font-mono text-xs text-(--text-muted)">
                                {member.id}
                              </Table.Cell>

                              {/* Name & Surname */}
                              <Table.Cell>
                                <div className="flex items-center gap-3">
                                  <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-(--color-brand)/10 text-xs font-semibold text-(--color-brand)">
                                    {member.name
                                      .split(" ")
                                      .map((n) => n[0])
                                      .join("")
                                      .toUpperCase()
                                      .slice(0, 2)}
                                  </div>
                                  <span className="font-medium text-(--text-primary)">
                                    {member.name}
                                  </span>
                                </div>
                              </Table.Cell>

                              {/* Roles */}
                              <Table.Cell>
                                <div className="flex flex-wrap gap-2">
                                  {member.roles.map((role) => (
                                    <Badge 
                                      key={role} 
                                      variant="outline"
                                      className={cn(
                                        "rounded-md px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider",
                                        role === "Owner" ? "border-amber-200 bg-amber-50 text-amber-700" :
                                        role === "Admin" ? "border-indigo-200 bg-indigo-50 text-indigo-700" :
                                        "border-(--border-subtle) bg-(--bg-subtle) text-(--text-muted)"
                                      )}
                                    >
                                      {role}
                                    </Badge>
                                  ))}
                                </div>
                              </Table.Cell>

                              {/* Gmail (masked) */}
                              <Table.Cell className="text-(--text-muted) whitespace-nowrap">
                                <div className="flex items-center gap-1.5">
                                  <span className={emailVisible ? "" : "select-none"}>
                                    {emailVisible ? member.gmail : maskGoogle(member.gmail)}
                                  </span>
                                  <button
                                    type="button"
                                    onClick={() => toggleEmailVisibility(member.id)}
                                    className={cn(iconBtnClasses, "flex-shrink-0")}
                                    aria-label={emailVisible ? "Hide email" : "Show email"}
                                    aria-pressed={emailVisible}
                                  >
                                    {emailVisible ? (
                                      <EyeSlash size={14} aria-hidden="true" />
                                    ) : (
                                      <Eye size={14} aria-hidden="true" />
                                    )}
                                  </button>
                                </div>
                              </Table.Cell>

                              {/* Password (masked, with auto-gen logic) */}
                              <Table.Cell className="text-(--text-muted) whitespace-nowrap">
                                <div className="flex items-center gap-1.5">
                                  <span className={passwordVisible ? "font-mono text-xs" : "select-none"}>
                                    {passwordVisible && canShowPassword
                                      ? member.password
                                      : maskValue(member.password)}
                                  </span>
                                  {canShowPassword ? (
                                    <button
                                      type="button"
                                      onClick={() => togglePasswordVisibility(member.id)}
                                      className={cn(iconBtnClasses, "flex-shrink-0")}
                                      aria-label={passwordVisible ? "Hide password" : "Show password"}
                                      aria-pressed={passwordVisible}
                                    >
                                      {passwordVisible ? (
                                        <EyeSlash size={14} aria-hidden="true" />
                                      ) : (
                                        <Eye size={14} aria-hidden="true" />
                                      )}
                                    </button>
                                  ) : null}
                                </div>
                              </Table.Cell>

                              {/* Notes */}
                              <Table.Cell className="max-w-[200px] truncate text-(--text-muted)">
                                {member.notes || "\u2014"}
                              </Table.Cell>

                              {/* Created */}
                              <Table.Cell className="whitespace-nowrap tabular-nums">
                                <div className="flex flex-col">
                                  <span className="text-sm text-(--text-primary)">
                                    {formatDate(member.createdAt).date}
                                  </span>
                                  <span className="text-xs text-(--text-muted)">
                                    {formatDate(member.createdAt).time}
                                  </span>
                                </div>
                              </Table.Cell>

                              {/* Actions */}
                              <Table.Cell className="min-w-[120px] text-right pr-6">
                                <div className="flex items-center justify-end gap-3.5">
                                  {isPrivileged ? (
                                    <>
                                      <button
                                        type="button"
                                        onClick={() => handleEditMember(member)}
                                        className={cn(iconBtnClasses, "flex-shrink-0")}
                                        aria-label={`Edit ${member.name}`}
                                      >
                                        <PencilSimple size={14} weight="bold" aria-hidden="true" />
                                      </button>
                                      <button
                                        type="button"
                                        onClick={() => handleDeleteMember(member)}
                                        className={cn(
                                          iconBtnClasses,
                                          "flex-shrink-0 hover:bg-(--status-destructive-bg) hover:text-(--color-destructive)",
                                        )}
                                        aria-label={`Delete ${member.name}`}
                                      >
                                        <Trash size={14} weight="bold" aria-hidden="true" />
                                      </button>
                                    </>
                                  ) : (
                                    <>
                                      <button
                                        type="button"
                                        className={cn(iconBtnClasses, "flex-shrink-0")}
                                        aria-label={`Suggest edit for ${member.name}`}
                                        title="Suggest Edit"
                                      >
                                        <PencilSimple size={14} weight="bold" aria-hidden="true" />
                                      </button>
                                      <button
                                        type="button"
                                        className={cn(
                                          iconBtnClasses,
                                          "flex-shrink-0 hover:bg-(--status-destructive-bg) hover:text-(--color-destructive)",
                                        )}
                                        aria-label={`Suggest deletion for ${member.name}`}
                                        title="Suggest Deletion"
                                      >
                                        <Trash size={14} weight="bold" aria-hidden="true" />
                                      </button>
                                    </>
                                  )}
                                </div>
                              </Table.Cell>
                            </Table.Row>
                          );
                        })
                      ) : (
                        <Table.Row className="hover:bg-transparent hover:shadow-none">
                          <Table.Cell
                            colSpan={COLUMN_COUNT}
                            className="py-12 text-center text-sm text-(--text-muted)"
                          >
                            No members match your search query.
                          </Table.Cell>
                        </Table.Row>
                      )}
                    </Table.Body>
                  </Table>
                </div>

                {/* ── Pagination ── */}
                <div className="mt-2 flex items-center justify-between px-1">
                  <div className="text-xs text-(--text-muted)">
                    {filteredMembers.length} of {members.length} members
                  </div>
                  {totalPages > 1 && (
                    <Pagination currentPage={page} totalPages={totalPages} onPageChange={setPage}>
                      <Pagination.Prev />
                      <Pagination.Pages />
                      <Pagination.Next />
                    </Pagination>
                  )}
                </div>
              </>
            ) : (
              /* ── Suggestions Tab ── */
              <div className="overflow-hidden rounded-xl border border-(--border-subtle-plus) bg-(--bg-base) shadow-[var(--shadow-subtle)]">
                <Table>
                  <Table.Header>
                    <Table.Row className="bg-(--bg-subtle)/60 hover:bg-(--bg-subtle)/60 hover:shadow-none">
                      <Table.Head className="text-xs uppercase tracking-wider text-(--text-muted)">Type</Table.Head>
                      <Table.Head className="text-xs uppercase tracking-wider text-(--text-muted)">Member</Table.Head>
                      <Table.Head className="text-xs uppercase tracking-wider text-(--text-muted)">Title</Table.Head>
                      <Table.Head className="text-xs uppercase tracking-wider text-(--text-muted)">Requester</Table.Head>
                      <Table.Head className="text-xs uppercase tracking-wider text-(--text-muted)">Status</Table.Head>
                      <Table.Head className="text-xs uppercase tracking-wider text-(--text-muted)">Created</Table.Head>
                    </Table.Row>
                  </Table.Header>
                  <Table.Body>
                    {INITIAL_SUGGESTIONS.length > 0 ? (
                      INITIAL_SUGGESTIONS.map((suggestion) => (
                        <Table.Row key={suggestion.id}>
                          <Table.Cell>
                            <Badge
                              variant={
                                suggestion.type === "Delete"
                                  ? "destructive"
                                  : suggestion.type === "Edit"
                                    ? "warning"
                                    : "success"
                              }
                            >
                              {suggestion.type}
                            </Badge>
                          </Table.Cell>
                          <Table.Cell className="font-medium text-(--text-primary)">
                            {suggestion.memberName}
                          </Table.Cell>
                          <Table.Cell className="max-w-[240px] truncate text-(--text-muted)">
                            {suggestion.title}
                          </Table.Cell>
                          <Table.Cell className="text-(--text-muted)">
                            {suggestion.requester}
                          </Table.Cell>
                          <Table.Cell>
                            <Badge
                              variant={
                                suggestion.status === "Approved"
                                  ? "success"
                                  : suggestion.status === "Declined"
                                    ? "destructive"
                                    : suggestion.status === "In Review"
                                      ? "warning"
                                      : "info"
                              }
                            >
                              {suggestion.status}
                            </Badge>
                          </Table.Cell>
                          <Table.Cell className="whitespace-nowrap tabular-nums">
                            <div className="flex flex-col">
                              <span className="text-sm text-(--text-primary)">
                                {formatDate(suggestion.createdAt).date}
                              </span>
                              <span className="text-xs text-(--text-muted)">
                                {formatDate(suggestion.createdAt).time}
                              </span>
                            </div>
                          </Table.Cell>
                        </Table.Row>
                      ))
                    ) : (
                      <Table.Row className="hover:bg-transparent hover:shadow-none">
                        <Table.Cell
                           colSpan={6}
                           className="py-12 text-center text-sm text-(--text-muted)"
                        >
                           No suggestions pending.
                        </Table.Cell>
                      </Table.Row>
                    )}
                  </Table.Body>
                </Table>
              </div>
            )}
          </div>
        </main>
      </div>

      {/* ── Dialogs ── */}
      <MemberFormDialog
        open={formOpen}
        onOpenChange={setFormOpen}
        editingMember={editingMember}
        onSave={handleSaveForm}
      />
      <DeleteDialog
        open={deleteOpen}
        onOpenChange={setDeleteOpen}
        memberName={deletingMember?.name ?? ""}
        onConfirm={handleConfirmDelete}
      />
    </div>
  );
}
