export const VIEWER_ROLES = ["Owner", "Admin", "Moderator"] as const;
export const MEMBER_ROLES = ["Owner", "Admin", "Moderator", "Media Rep"] as const;
export const SUGGESTION_STATUSES = [
  "New",
  "In Review",
  "Approved",
  "Declined",
] as const;
export const DEPARTMENTS = ["Leadership", "Media", "Operations", "Content"] as const;

export type ViewerRole = (typeof VIEWER_ROLES)[number];
export type MemberRole = (typeof MEMBER_ROLES)[number];
export type SuggestionStatus = (typeof SUGGESTION_STATUSES)[number];
export type Department = (typeof DEPARTMENTS)[number];

export interface Member {
  id: string;
  name: string;
  roles: MemberRole[];
  gmail: string;
  password: string;
  notes: string;
  createdAt: string;
  department: Department;
  passwordAutoGenerated?: boolean;
}

export interface Suggestion {
  id: string;
  type: "Create" | "Edit" | "Delete";
  memberId?: string;
  memberName: string;
  title: string;
  description: string;
  department: Department;
  status: SuggestionStatus;
  createdAt: string;
  requester: string;
}

export const INITIAL_MEMBERS: Member[] = [
  {
    id: "M-001",
    name: "Paul Nekrasov",
    roles: ["Owner"],
    gmail: "paul@gmail.com",
    password: "ow7-11qa-pn",
    notes: "Founding owner with full approval access.",
    createdAt: "2024-11-02T09:30:00.000Z",
    department: "Leadership",
    passwordAutoGenerated: true,
  },
  {
    id: "M-002",
    name: "Amelia Koval",
    roles: ["Admin"],
    gmail: "amelia@gmail.com",
    password: "admin-4217-ak",
    notes: "Keeps daily operations and escalations moving.",
    createdAt: "2024-11-06T14:12:00.000Z",
    department: "Operations",
    passwordAutoGenerated: true,
  },
  {
    id: "M-003",
    name: "Danylo Hrinchenko",
    roles: ["Moderator"],
    gmail: "danylo@gmail.com",
    password: "moder8-dh-04",
    notes: "Reviews media changes and resolves queue blockers.",
    createdAt: "2024-11-12T08:45:00.000Z",
    department: "Media",
  },
  {
    id: "M-004",
    name: "Lina Petrenko",
    roles: ["Media Rep"],
    gmail: "lina@gmail.com",
    password: "media-lp-082",
    notes: "Publishes weekly announcements and release notes.",
    createdAt: "2024-11-13T12:18:00.000Z",
    department: "Media",
  },
  {
    id: "M-005",
    name: "Marta Kovalenko",
    roles: ["Admin", "Moderator"],
    gmail: "marta@gmail.com",
    password: "mk-admin-212",
    notes: "Owns moderation playbooks for cross-team launches.",
    createdAt: "2024-11-18T16:02:00.000Z",
    department: "Content",
  },
  {
    id: "M-006",
    name: "Oleksii Romanov",
    roles: ["Moderator"],
    gmail: "oleksii@gmail.com",
    password: "ops-rom-845",
    notes: "Supports incident routing and access clean-up.",
    createdAt: "2024-11-22T07:57:00.000Z",
    department: "Operations",
  },
  {
    id: "M-007",
    name: "Iryna Melnyk",
    roles: ["Media Rep"],
    gmail: "iryna@gmail.com",
    password: "copy-im-300",
    notes: "Owns publication QA and issue recaps.",
    createdAt: "2024-11-26T10:26:00.000Z",
    department: "Content",
  },
  {
    id: "M-008",
    name: "Bohdan Sydorenko",
    roles: ["Moderator", "Media Rep"],
    gmail: "bohdan@gmail.com",
    password: "queue-bs-661",
    notes: "Bridges suggestions between review and publishing.",
    createdAt: "2024-11-29T11:41:00.000Z",
    department: "Media",
  },
];

export const INITIAL_SUGGESTIONS: Suggestion[] = [
  {
    id: "SUG-001",
    type: "Delete",
    memberId: "M-004",
    memberName: "Lina Petrenko",
    title: "Remove duplicate media seat",
    description:
      "Delete Lina Petrenko from the Media roster after the merged publication workflow ships.",
    department: "Media",
    status: "New",
    createdAt: "2024-12-01T09:20:00.000Z",
    requester: "Danylo Hrinchenko",
  },
  {
    id: "SUG-002",
    type: "Edit",
    memberId: "M-008",
    memberName: "Bohdan Sydorenko",
    title: "Expand moderator coverage",
    description:
      "Update Bohdan Sydorenko with broader moderator permissions during the winter campaign.",
    department: "Media",
    status: "In Review",
    createdAt: "2024-12-02T12:05:00.000Z",
    requester: "Marta Kovalenko",
  },
  {
    id: "SUG-003",
    type: "Create",
    memberName: "Backup owner seat",
    title: "Create backup owner seat",
    description:
      "Add an emergency owner account for leadership continuity on release nights.",
    department: "Leadership",
    status: "New",
    createdAt: "2024-12-03T08:40:00.000Z",
    requester: "Amelia Koval",
  },
  {
    id: "SUG-004",
    type: "Delete",
    memberId: "M-006",
    memberName: "Oleksii Romanov",
    title: "Archive old operations access",
    description:
      "Remove unused moderator access from the previous operations onboarding track.",
    department: "Operations",
    status: "Approved",
    createdAt: "2024-12-04T15:18:00.000Z",
    requester: "Paul Nekrasov",
  },
];
