"use client";

import React, {
  startTransition,
  useDeferredValue,
  useEffect,
  useRef,
  useState,
} from "react";
import {
  ArrowsClockwise,
  CaretDown,
  Check,
  Eye,
  EyeSlash,
  FunnelSimple,
  MagnifyingGlass,
  PencilSimple,
  Plus,
  ShieldCheck,
  Trash,
  UsersThree,
} from "@phosphor-icons/react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Table } from "@components/layout/table";
import { Button } from "@components/ui/Button";
import { IconButton } from "@components/ui/IconButton";
import { Pagination } from "@components/ui/pagination";
import { Badge } from "@components/ui/Badge";
import { Dialog } from "@components/ui/Dialog";
import { Tabs } from "@components/ui/Tabs";
import {
  Department,
  DEPARTMENTS,
  INITIAL_MEMBERS,
  INITIAL_SUGGESTIONS,
  MEMBER_ROLES,
  Member,
  MemberRole,
  SUGGESTION_STATUSES,
  Suggestion,
  SuggestionStatus,
  VIEWER_ROLES,
  ViewerRole,
} from "./roles-data";

function cn(...classes: (string | undefined | null | false)[]) {
  return classes.filter(Boolean).join(" ");
}

interface VerificationChallenge {
  left: number;
  right: number;
  answer: number;
}

interface MemberFormState {
  name: string;
  roles: MemberRole[];
  gmail: string;
  password: string;
  notes: string;
  passwordAutoGenerated: boolean;
  verificationAnswer: string;
}

type MemberFormErrors = Partial<
  Record<"name" | "roles" | "gmail" | "password" | "verification", string>
>;

type DialogState =
  | { type: "create" }
  | { type: "edit"; memberId: string }
  | { type: "delete"; memberId: string }
  | null;

const PAGE_SIZE = 5;
const VIEWER_REQUESTERS: Record<ViewerRole, string> = {
  Owner: "Paul Nekrasov",
  Admin: "Amelia Koval",
  Moderator: "Danylo Hrinchenko",
};

const roleBadgeVariants: Record<MemberRole, "destructive" | "brand" | "warning" | "info"> = {
  Owner: "destructive",
  Admin: "brand",
  Moderator: "warning",
  "Media Rep": "info",
};

const suggestionStatusVariants: Record<
  SuggestionStatus,
  "neutral" | "warning" | "success" | "destructive"
> = {
  New: "neutral",
  "In Review": "warning",
  Approved: "success",
  Declined: "destructive",
};

function isViewerRole(value: string | null): value is ViewerRole {
  return VIEWER_ROLES.includes(value as ViewerRole);
}

function isMemberRole(value: string | null): value is MemberRole {
  return MEMBER_ROLES.includes(value as MemberRole);
}

function formatDateLabel(value: string) {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(value));
}

function formatTimeLabel(value: string) {
  return new Intl.DateTimeFormat("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(value));
}

function formatDateTimeLabel(value: string) {
  return `${formatDateLabel(value)} at ${formatTimeLabel(value)}`;
}

function getInitials(name: string) {
  return name
    .split(" ")
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? "")
    .join("");
}

function maskEmail(value: string) {
  const [name, domain] = value.split("@");
  const maskedName = `${name.slice(0, 2)}${"•".repeat(Math.max(name.length - 2, 3))}`;
  return `${maskedName}@${domain}`;
}

function maskPassword(value: string) {
  return "•".repeat(Math.max(value.length, 8));
}

function generatePassword() {
  return `${Math.random().toString(36).slice(2, 6)}-${Math.random()
    .toString(36)
    .slice(2, 6)}-${Math.random().toString(36).slice(2, 4)}`;
}

function createVerificationChallenge(): VerificationChallenge {
  const left = Math.floor(Math.random() * 7) + 3;
  const right = Math.floor(Math.random() * 8) + 2;

  return {
    left,
    right,
    answer: left + right,
  };
}

function inferDepartment(roles: MemberRole[]): Department {
  if (roles.includes("Owner")) return "Leadership";
  if (roles.includes("Moderator") || roles.includes("Media Rep")) return "Media";
  if (roles.includes("Admin")) return "Operations";
  return "Content";
}

function createMemberFormState(member?: Member): MemberFormState {
  return {
    name: member?.name ?? "",
    roles: member?.roles ?? [],
    gmail: member?.gmail ?? "",
    password: member?.password ?? generatePassword(),
    notes: member?.notes ?? "",
    passwordAutoGenerated: member?.passwordAutoGenerated ?? !member,
    verificationAnswer: "",
  };
}

function validateMemberForm(formState: MemberFormState): MemberFormErrors {
  const errors: MemberFormErrors = {};

  if (!formState.name.trim()) errors.name = "Enter the member's full name.";
  if (formState.roles.length === 0) errors.roles = "Select at least one access role.";
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formState.gmail.trim().toLowerCase())) {
    errors.gmail = "Use a valid email address.";
  }
  if (!formState.password.trim()) errors.password = "Add a password or generate a new one.";

  return errors;
}

function buildHref(
  pathname: string,
  searchParams: URLSearchParams,
  updates: Record<string, string | undefined>,
) {
  const params = new URLSearchParams(searchParams.toString());

  Object.entries(updates).forEach(([key, value]) => {
    if (!value) {
      params.delete(key);
      return;
    }

    params.set(key, value);
  });

  const search = params.toString();
  return search ? `${pathname}?${search}` : pathname;
}

function nextMemberId(members: Member[]) {
  const maxId = members.reduce((highest, member) => {
    const numericPart = Number.parseInt(member.id.replace("M-", ""), 10);
    return Number.isNaN(numericPart) ? highest : Math.max(highest, numericPart);
  }, 0);

  return `M-${String(maxId + 1).padStart(3, "0")}`;
}

function nextSuggestionId(suggestions: Suggestion[]) {
  const maxId = suggestions.reduce((highest, suggestion) => {
    const numericPart = Number.parseInt(suggestion.id.replace("SUG-", ""), 10);
    return Number.isNaN(numericPart) ? highest : Math.max(highest, numericPart);
  }, 0);

  return `SUG-${String(maxId + 1).padStart(3, "0")}`;
}

function StatusBanner({
  tone,
  message,
}: {
  tone: "success" | "info";
  message: string;
}) {
  return (
    <div
      aria-live="polite"
      className={cn(
        "flex items-center gap-3 rounded-2xl border px-4 py-3 text-sm",
        tone === "success"
          ? "border-(--status-success-border) bg-(--status-success-bg) text-(--color-success)"
          : "border-(--status-info-border) bg-(--status-info-bg) text-(--color-info)",
      )}
    >
      <ShieldCheck size={18} weight="bold" aria-hidden="true" />
      <span>{message}</span>
    </div>
  );
}

function EmptyState({
  title,
  description,
  action,
}: {
  title: string;
  description: string;
  action?: React.ReactNode;
}) {
  return (
    <div className="flex flex-col items-center justify-center gap-4 rounded-[28px] border border-(--border-subtle-plus) bg-(--bg-base) px-6 py-12 text-center shadow-[var(--shadow-subtle)]">
      <div className="flex h-16 w-16 items-center justify-center rounded-[20px] border border-(--border-subtle-plus) bg-(--bg-subtle) text-(--text-muted) shadow-[var(--shadow-subtle)]">
        <UsersThree size={28} weight="bold" aria-hidden="true" />
      </div>
      <div className="max-w-xl space-y-2">
        <h3 className="text-balance text-xl font-semibold tracking-[-0.03em] text-(--text-primary)">
          {title}
        </h3>
        <p className="text-pretty text-sm leading-6 text-(--text-muted)">{description}</p>
      </div>
      {action}
    </div>
  );
}

export default function RolesPage() {
  const pathname = usePathname();
  const router = useRouter();
  const searchParams = useSearchParams();

  const [members, setMembers] = useState(INITIAL_MEMBERS);
  const [suggestions, setSuggestions] = useState(INITIAL_SUGGESTIONS);
  const [dialogState, setDialogState] = useState<DialogState>(null);
  const [formState, setFormState] = useState<MemberFormState | null>(null);
  const [formErrors, setFormErrors] = useState<MemberFormErrors>({});
  const [verificationChallenge, setVerificationChallenge] = useState(
    createVerificationChallenge(),
  );
  const [feedback, setFeedback] = useState<{
    tone: "success" | "info";
    message: string;
  } | null>(null);
  const [filterOpen, setFilterOpen] = useState(false);
  const [roleMenuOpen, setRoleMenuOpen] = useState(false);
  const [revealedEmails, setRevealedEmails] = useState<Record<string, boolean>>({});
  const [revealedPasswords, setRevealedPasswords] = useState<Record<string, boolean>>({});
  const filterPanelRef = useRef<HTMLDivElement>(null);
  const filterButtonRef = useRef<HTMLButtonElement>(null);
  const roleMenuRef = useRef<HTMLDivElement>(null);
  const nameInputRef = useRef<HTMLInputElement>(null);

  const tab = searchParams.get("tab") === "suggestions" ? "suggestions" : "members";
  const viewerRole = isViewerRole(searchParams.get("viewer"))
    ? (searchParams.get("viewer") as ViewerRole)
    : "Owner";
  const searchValue = searchParams.get("q") ?? "";
  const memberIdFilter = searchParams.get("member") ?? "";
  const roleFilter = isMemberRole(searchParams.get("role"))
    ? (searchParams.get("role") as MemberRole)
    : "";
  const fromFilter = searchParams.get("from") ?? "";
  const toFilter = searchParams.get("to") ?? "";
  const safeDepartment = searchParams.get("department");
  const departmentFilter =
    viewerRole === "Moderator"
      ? "Media"
      : safeDepartment && ["All", ...DEPARTMENTS].includes(safeDepartment)
        ? safeDepartment
        : "All";
  const parsedPage = Number.parseInt(searchParams.get("page") ?? "1", 10);
  const page = Number.isNaN(parsedPage) || parsedPage < 1 ? 1 : parsedPage;
  const deferredSearch = useDeferredValue(searchValue.trim().toLowerCase());

  const currentMember =
    dialogState && dialogState.type !== "create"
      ? members.find((member) => member.id === dialogState.memberId) ?? null
      : null;
  const directMutation = viewerRole === "Owner" || viewerRole === "Admin";
  const pendingSuggestionsCount = suggestions.filter(
    (suggestion) =>
      suggestion.status === "New" || suggestion.status === "In Review",
  ).length;

  const updateQuery = (updates: Record<string, string | undefined>) => {
    startTransition(() => {
      router.replace(buildHref(pathname, new URLSearchParams(searchParams.toString()), updates), {
        scroll: false,
      });
    });
  };

  useEffect(() => {
    if (!feedback) {
      return undefined;
    }

    const timeout = window.setTimeout(() => {
      setFeedback(null);
    }, 3200);

    return () => window.clearTimeout(timeout);
  }, [feedback]);

  useEffect(() => {
    const handlePointerDown = (event: MouseEvent) => {
      const target = event.target as Node;

      if (
        filterOpen &&
        !filterPanelRef.current?.contains(target) &&
        !filterButtonRef.current?.contains(target)
      ) {
        setFilterOpen(false);
      }

      if (roleMenuOpen && !roleMenuRef.current?.contains(target)) {
        setRoleMenuOpen(false);
      }
    };

    document.addEventListener("mousedown", handlePointerDown);
    return () => document.removeEventListener("mousedown", handlePointerDown);
  }, [filterOpen, roleMenuOpen]);

  const filteredMembers = members.filter((member) => {
    const matchesSearch =
      deferredSearch.length === 0 ||
      member.id.toLowerCase().includes(deferredSearch) ||
      member.name.toLowerCase().includes(deferredSearch) ||
      member.gmail.toLowerCase().includes(deferredSearch);
    const matchesMemberId =
      memberIdFilter.length === 0 ||
      member.id.toLowerCase().includes(memberIdFilter.toLowerCase());
    const matchesRole = roleFilter ? member.roles.includes(roleFilter) : true;
    const matchesFrom = fromFilter.length === 0 || member.createdAt >= `${fromFilter}T00:00:00.000Z`;
    const matchesTo = toFilter.length === 0 || member.createdAt <= `${toFilter}T23:59:59.999Z`;

    return matchesSearch && matchesMemberId && matchesRole && matchesFrom && matchesTo;
  });

  const totalPages = Math.max(1, Math.ceil(filteredMembers.length / PAGE_SIZE));
  const currentPage = Math.min(page, totalPages);
  const pageStart = (currentPage - 1) * PAGE_SIZE;
  const visibleMembers = filteredMembers.slice(pageStart, pageStart + PAGE_SIZE);
  const activeFilterCount = [
    searchValue,
    memberIdFilter,
    roleFilter,
    fromFilter,
    toFilter,
  ].filter(Boolean).length;

  const visibleSuggestions = suggestions
    .filter((suggestion) =>
      viewerRole === "Moderator" ? suggestion.department === "Media" : true,
    )
    .filter((suggestion) =>
      departmentFilter === "All" ? true : suggestion.department === departmentFilter,
    );

  const departmentTabs =
    viewerRole === "Moderator" ? ["Media"] : (["All", ...DEPARTMENTS] as const);

  const openCreateDialog = () => {
    setDialogState({ type: "create" });
    setFormState(createMemberFormState());
    setFormErrors({});
    setRoleMenuOpen(false);
    setVerificationChallenge(createVerificationChallenge());
  };

  const openEditDialog = (member: Member) => {
    setDialogState({ type: "edit", memberId: member.id });
    setFormState(createMemberFormState(member));
    setFormErrors({});
    setRoleMenuOpen(false);
    setVerificationChallenge(createVerificationChallenge());
  };

  const openDeleteDialog = (member: Member) => {
    setDialogState({ type: "delete", memberId: member.id });
    setFormState({
      name: "",
      roles: [],
      gmail: "",
      password: "",
      notes: "",
      passwordAutoGenerated: false,
      verificationAnswer: "",
    });
    setFormErrors({});
    setRoleMenuOpen(false);
    setVerificationChallenge(createVerificationChallenge());
  };

  const closeDialog = () => {
    setDialogState(null);
    setFormState(null);
    setFormErrors({});
    setRoleMenuOpen(false);
  };

  const submitSuggestion = ({
    type,
    memberId,
    memberName,
    description,
    department,
  }: {
    type: Suggestion["type"];
    memberId?: string;
    memberName: string;
    description: string;
    department: Member["department"];
  }) => {
    setSuggestions((currentSuggestions) => [
      {
        id: nextSuggestionId(currentSuggestions),
        type,
        memberId,
        memberName,
        title:
          type === "Create"
            ? `Create ${memberName}`
            : type === "Edit"
              ? `Edit ${memberName}`
              : `Delete ${memberName}`,
        description,
        department,
        status: "New",
        createdAt: new Date().toISOString(),
        requester: VIEWER_REQUESTERS[viewerRole],
      },
      ...currentSuggestions,
    ]);
  };

  const handleRoleToggle = (role: MemberRole) => {
    if (!formState) {
      return;
    }

    const nextRoles = formState.roles.includes(role)
      ? formState.roles.filter((item) => item !== role)
      : [...formState.roles, role];

    setFormState({
      ...formState,
      roles: nextRoles,
    });
  };

  const handleMemberSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (!formState || !dialogState || dialogState.type === "delete") {
      return;
    }

    const validationErrors = validateMemberForm(formState);

    if (
      directMutation &&
      Number.parseInt(formState.verificationAnswer, 10) !== verificationChallenge.answer
    ) {
      validationErrors.verification = "Wrong answer - try again.";
    }

    setFormErrors(validationErrors);

    if (Object.keys(validationErrors).length > 0) {
      return;
    }

    const sanitizedMember = {
      name: formState.name.trim(),
      roles: formState.roles,
      gmail: formState.gmail.trim().toLowerCase(),
      password: formState.password.trim(),
      notes: formState.notes.trim(),
      department: inferDepartment(formState.roles),
      passwordAutoGenerated: formState.passwordAutoGenerated,
    };

    if (!directMutation) {
      submitSuggestion({
        type: dialogState.type === "create" ? "Create" : "Edit",
        memberId: dialogState.type === "edit" ? dialogState.memberId : undefined,
        memberName: sanitizedMember.name,
        description:
          dialogState.type === "create"
            ? `Create member access for ${sanitizedMember.name} with ${sanitizedMember.roles.join(
                ", ",
              )} permissions.`
            : `Update ${sanitizedMember.name} and sync ${sanitizedMember.roles.join(
                ", ",
              )} access roles.`,
        department: sanitizedMember.department,
      });

      setFeedback({
        tone: "info",
        message:
          dialogState.type === "create"
            ? "Create request sent to the review queue."
            : "Edit request sent to the review queue.",
      });
      closeDialog();
      updateQuery({ tab: "suggestions" });
      return;
    }

    if (dialogState.type === "create") {
      const nextMember: Member = {
        id: nextMemberId(members),
        createdAt: new Date().toISOString(),
        ...sanitizedMember,
      };

      setMembers((currentMembers) => [nextMember, ...currentMembers]);
      setFeedback({
        tone: "success",
        message: `${nextMember.name} was added to the roles roster.`,
      });
    } else {
      setMembers((currentMembers) =>
        currentMembers.map((member) =>
          member.id === dialogState.memberId
            ? {
                ...member,
                ...sanitizedMember,
              }
            : member,
        ),
      );
      setFeedback({
        tone: "success",
        message: `${sanitizedMember.name} was updated successfully.`,
      });
    }

    closeDialog();
  };

  const handleDeleteConfirm = () => {
    if (!dialogState || dialogState.type !== "delete" || !currentMember) {
      return;
    }

    if (
      directMutation &&
      Number.parseInt(formState?.verificationAnswer ?? "", 10) !== verificationChallenge.answer
    ) {
      setFormErrors({ verification: "Wrong answer - try again." });
      return;
    }

    if (!directMutation) {
      submitSuggestion({
        type: "Delete",
        memberId: currentMember.id,
        memberName: currentMember.name,
        description: `Delete ${currentMember.name} from the ${currentMember.department} roster after reviewer approval.`,
        department: currentMember.department,
      });
      setFeedback({
        tone: "info",
        message: "Delete request sent to the review queue.",
      });
      closeDialog();
      updateQuery({ tab: "suggestions" });
      return;
    }

    setMembers((currentMembers) =>
      currentMembers.filter((member) => member.id !== currentMember.id),
    );
    setFeedback({
      tone: "success",
      message: `${currentMember.name} was removed from the roster.`,
    });
    closeDialog();
  };

  const handleSuggestionStatusChange = (
    suggestionId: string,
    nextStatus: SuggestionStatus,
  ) => {
    setSuggestions((currentSuggestions) =>
      currentSuggestions.map((suggestion) =>
        suggestion.id === suggestionId
          ? {
              ...suggestion,
              status: nextStatus,
            }
          : suggestion,
      ),
    );

    setFeedback({
      tone: "info",
      message: `Suggestion ${suggestionId} moved to ${nextStatus}.`,
    });
  };

  return (
    <section className="flex flex-col gap-6">
      {feedback ? <StatusBanner tone={feedback.tone} message={feedback.message} /> : null}

      <div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between">
        <div className="max-w-3xl">
          <Badge variant="brand" size="md">
            Role management
          </Badge>
          <h2 className="mt-4 text-balance text-[clamp(2rem,4vw,2.6rem)] font-semibold tracking-[-0.05em] text-(--text-primary)">
            Roles
          </h2>
          <p className="mt-3 max-w-2xl text-pretty text-sm leading-6 text-(--text-muted) sm:text-base">
            Manage direct member access for owners and admins, then flip into moderator mode to review the suggestion flow before anything destructive ships.
          </p>
          <div className="mt-4 flex flex-wrap items-center gap-2">
            <Badge variant="neutral" size="md">
              {members.length} members
            </Badge>
            <Badge variant="neutral" size="md">
              {pendingSuggestionsCount} pending suggestions
            </Badge>
            {activeFilterCount > 0 ? (
              <Badge variant="brand" size="md">
                {activeFilterCount} active filters
              </Badge>
            ) : null}
          </div>
        </div>

        <div className="flex w-full flex-col gap-3 xl:max-w-md xl:items-end">
          <div className="w-full rounded-[22px] border border-(--border-subtle-plus) bg-(--bg-base) p-1 shadow-[var(--shadow-subtle)] xl:w-auto">
            <div className="grid grid-cols-3 gap-1">
              {VIEWER_ROLES.map((role) => {
                const active = viewerRole === role;

                return (
                  <button
                    key={role}
                    type="button"
                    className={cn(
                      "rounded-2xl px-4 py-2.5 text-sm font-medium transition-[background-color,color,box-shadow] duration-150 ease-out focus-visible:outline-none focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]",
                      active
                        ? "bg-(--color-brand) text-(--text-on-accent) shadow-[var(--shadow-btn-primary)]"
                        : "text-(--text-muted) hover:bg-(--bg-subtle) hover:text-(--text-primary)",
                    )}
                    onClick={() =>
                      updateQuery({
                        viewer: role,
                        department: role === "Moderator" ? "Media" : undefined,
                        page: "1",
                      })
                    }
                  >
                    {role}
                  </button>
                );
              })}
            </div>
          </div>

          <Button
            iconLeft={<Plus size={16} weight="bold" aria-hidden="true" />}
            onClick={openCreateDialog}
          >
            Create Role
          </Button>
        </div>
      </div>

      <Tabs
        value={tab}
        onValueChange={(nextTab) =>
          updateQuery({
            tab: nextTab,
            page: "1",
            department:
              nextTab === "suggestions"
                ? viewerRole === "Moderator"
                  ? "Media"
                  : departmentFilter === "All"
                    ? undefined
                    : departmentFilter
                : undefined,
          })
        }
      >
        <Tabs.List>
          <Tabs.Trigger
            value="members"
            icon={<UsersThree size={16} weight="bold" />}
          >
            Members
          </Tabs.Trigger>
          <Tabs.Trigger
            value="suggestions"
            icon={<ShieldCheck size={16} weight="bold" />}
            count={pendingSuggestionsCount}
          >
            Suggestions
          </Tabs.Trigger>
        </Tabs.List>

        <Tabs.Panel value="members" className="flex flex-col gap-6">
          <div className="rounded-[28px] border border-(--border-subtle-plus) bg-(--bg-base) p-5 shadow-[var(--shadow-subtle)]">
            <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
              <div className="flex flex-1 flex-col gap-3 sm:flex-row sm:items-center">
                <div className="relative w-full max-w-xl">
                  <MagnifyingGlass
                    size={16}
                    weight="bold"
                    aria-hidden="true"
                    className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-(--text-muted)"
                  />
                  <input
                    type="search"
                    name="roles-search"
                    value={searchValue}
                    onChange={(event) =>
                      updateQuery({
                        q: event.target.value || undefined,
                        page: "1",
                      })
                    }
                    placeholder="Search by name, ID, or email…"
                    className="min-h-12 w-full rounded-2xl border border-(--border-subtle) bg-(--bg-base) py-3 pl-11 pr-4 text-sm text-(--text-primary) placeholder:text-(--text-subtle) transition-[border-color,box-shadow] duration-150 ease-out focus-visible:outline-none focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]"
                  />
                </div>
                <div className="relative" ref={filterPanelRef}>
                  <Button
                    ref={filterButtonRef}
                    variant="secondary"
                    iconLeft={<FunnelSimple size={16} weight="bold" aria-hidden="true" />}
                    onClick={() => setFilterOpen((open) => !open)}
                  >
                    Filter
                  </Button>

                  {filterOpen ? (
                    <div className="absolute right-0 top-[calc(100%+0.75rem)] z-30 w-[320px] rounded-[24px] border border-(--border-subtle-plus) bg-(--bg-base) p-4 shadow-[var(--shadow-subtle-active)]">
                      <div className="space-y-4">
                        <div className="space-y-1.5">
                          <label
                            htmlFor="member-id-filter"
                            className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-muted)"
                          >
                            Member ID
                          </label>
                          <input
                            id="member-id-filter"
                            type="text"
                            value={memberIdFilter}
                            onChange={(event) =>
                              updateQuery({
                                member: event.target.value || undefined,
                                page: "1",
                              })
                            }
                            placeholder="e.g. M-001"
                            className="min-h-11 w-full rounded-2xl border border-(--border-subtle) bg-(--bg-base) px-4 py-3 text-sm text-(--text-primary) placeholder:text-(--text-subtle) transition-[border-color,box-shadow] duration-150 ease-out focus-visible:outline-none focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]"
                          />
                        </div>

                        <div className="space-y-2">
                          <p className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-muted)">
                            Access role
                          </p>
                          <div className="flex flex-wrap gap-2">
                            {MEMBER_ROLES.map((role) => {
                              const active = roleFilter === role;

                              return (
                                <button
                                  key={role}
                                  type="button"
                                  className={cn(
                                    "rounded-full border px-3 py-1.5 text-xs font-medium transition-[background-color,color,border-color,box-shadow] duration-150 ease-out focus-visible:outline-none focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]",
                                    active
                                      ? "border-(--border-brand) bg-(--color-brand)/10 text-(--text-accent)"
                                      : "border-(--border-subtle-plus) bg-(--bg-subtle) text-(--text-muted) hover:border-(--border-brand) hover:text-(--text-primary)",
                                  )}
                                  onClick={() =>
                                    updateQuery({
                                      role: active ? undefined : role,
                                      page: "1",
                                    })
                                  }
                                >
                                  {role}
                                </button>
                              );
                            })}
                          </div>
                        </div>

                        <div className="grid grid-cols-2 gap-3">
                          <div className="space-y-1.5">
                            <label
                              htmlFor="from-filter"
                              className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-muted)"
                            >
                              Created from
                            </label>
                            <input
                              id="from-filter"
                              type="date"
                              value={fromFilter}
                              onChange={(event) =>
                                updateQuery({
                                  from: event.target.value || undefined,
                                  page: "1",
                                })
                              }
                              className="min-h-11 w-full rounded-2xl border border-(--border-subtle) bg-(--bg-base) px-4 py-3 text-sm text-(--text-primary) transition-[border-color,box-shadow] duration-150 ease-out focus-visible:outline-none focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]"
                            />
                          </div>
                          <div className="space-y-1.5">
                            <label
                              htmlFor="to-filter"
                              className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-muted)"
                            >
                              Created to
                            </label>
                            <input
                              id="to-filter"
                              type="date"
                              value={toFilter}
                              onChange={(event) =>
                                updateQuery({
                                  to: event.target.value || undefined,
                                  page: "1",
                                })
                              }
                              className="min-h-11 w-full rounded-2xl border border-(--border-subtle) bg-(--bg-base) px-4 py-3 text-sm text-(--text-primary) transition-[border-color,box-shadow] duration-150 ease-out focus-visible:outline-none focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]"
                            />
                          </div>
                        </div>

                        <div className="flex items-center justify-between gap-3 pt-1">
                          <button
                            type="button"
                            className="text-sm font-medium text-(--text-muted) transition-colors duration-150 ease-out hover:text-(--text-primary)"
                            onClick={() => {
                              updateQuery({
                                q: undefined,
                                member: undefined,
                                role: undefined,
                                from: undefined,
                                to: undefined,
                                page: "1",
                              });
                              setFilterOpen(false);
                            }}
                          >
                            Clear filters
                          </button>
                          <Button variant="secondary" onClick={() => setFilterOpen(false)}>
                            Done
                          </Button>
                        </div>
                      </div>
                    </div>
                  ) : null}
                </div>
              </div>

              <div className="flex flex-wrap items-center gap-2">
                <Badge variant="neutral" size="md">
                  {filteredMembers.length} visible
                </Badge>
                <Badge variant="neutral" size="md">
                  Viewing as {viewerRole}
                </Badge>
              </div>
            </div>
          </div>

          {filteredMembers.length === 0 ? (
            <EmptyState
              title="No members match the current filter set"
              description="Try widening the search, clearing the date range, or switching to a different viewer role to see the full roster again."
              action={
                <Button
                  variant="secondary"
                  iconLeft={<ArrowsClockwise size={16} weight="bold" aria-hidden="true" />}
                  onClick={() =>
                    updateQuery({
                      q: undefined,
                      member: undefined,
                      role: undefined,
                      from: undefined,
                      to: undefined,
                      page: "1",
                    })
                  }
                >
                  Reset filters
                </Button>
              }
            />
          ) : (
            <div className="overflow-hidden rounded-[28px] border border-(--border-subtle-plus) bg-(--bg-base) shadow-[var(--shadow-subtle)]">
              <Table className="min-w-[1120px]">
                <Table.Header>
                  <Table.Row className="hover:bg-transparent">
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      ID
                    </Table.Head>
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      Name &amp; Surname
                    </Table.Head>
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      Roles
                    </Table.Head>
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      Gmail
                    </Table.Head>
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      Password
                    </Table.Head>
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      Notes
                    </Table.Head>
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      Created
                    </Table.Head>
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      Actions
                    </Table.Head>
                  </Table.Row>
                </Table.Header>

                <Table.Body>
                  {visibleMembers.map((member) => (
                    <Table.Row key={member.id}>
                      <Table.Cell className="px-5 py-4 text-sm text-(--text-muted)">
                        {member.id}
                      </Table.Cell>
                      <Table.Cell className="px-5 py-4">
                        <div className="flex min-w-0 items-center gap-3">
                          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-(--color-brand)/10 text-sm font-semibold text-(--text-accent)">
                            {getInitials(member.name)}
                          </div>
                          <span className="truncate text-sm font-semibold text-(--text-primary)">
                            {member.name}
                          </span>
                        </div>
                      </Table.Cell>
                      <Table.Cell className="px-5 py-4">
                        <div className="flex flex-wrap gap-1.5">
                          {member.roles.map((role) => (
                            <Badge key={role} variant={roleBadgeVariants[role]}>
                              {role}
                            </Badge>
                          ))}
                        </div>
                      </Table.Cell>
                      <Table.Cell className="px-5 py-4">
                        <div className="flex items-center gap-2">
                          <span className="min-w-0 truncate font-mono text-sm text-(--text-muted)">
                            {revealedEmails[member.id] ? member.gmail : maskEmail(member.gmail)}
                          </span>
                          <IconButton
                            aria-label={
                              revealedEmails[member.id]
                                ? `Hide ${member.name}'s email`
                                : `Reveal ${member.name}'s email`
                            }
                            icon={revealedEmails[member.id] ? EyeSlash : Eye}
                            variant="secondary"
                            onClick={() =>
                              setRevealedEmails((currentState) => ({
                                ...currentState,
                                [member.id]: !currentState[member.id],
                              }))
                            }
                          />
                        </div>
                      </Table.Cell>
                      <Table.Cell className="px-5 py-4">
                        <div className="flex items-center gap-2">
                          <span className="min-w-0 truncate font-mono text-sm text-(--text-muted)">
                            {revealedPasswords[member.id]
                              ? member.password
                              : maskPassword(member.password)}
                          </span>
                          <IconButton
                            aria-label={
                              revealedPasswords[member.id]
                                ? `Hide ${member.name}'s password`
                                : `Reveal ${member.name}'s password`
                            }
                            icon={revealedPasswords[member.id] ? EyeSlash : Eye}
                            variant="secondary"
                            onClick={() =>
                              setRevealedPasswords((currentState) => ({
                                ...currentState,
                                [member.id]: !currentState[member.id],
                              }))
                            }
                          />
                        </div>
                      </Table.Cell>
                      <Table.Cell className="px-5 py-4">
                        <span className="block max-w-[220px] truncate text-sm text-(--text-muted)">
                          {member.notes}
                        </span>
                      </Table.Cell>
                      <Table.Cell className="px-5 py-4">
                        <div className="space-y-0.5 text-xs leading-5 text-(--text-muted) [font-variant-numeric:tabular-nums]">
                          <div>{formatDateLabel(member.createdAt)}</div>
                          <div>{formatTimeLabel(member.createdAt)}</div>
                        </div>
                      </Table.Cell>
                      <Table.Cell className="px-5 py-4">
                        <div className="flex items-center gap-2">
                          <IconButton
                            aria-label={`Edit ${member.name}`}
                            icon={PencilSimple}
                            variant="secondary"
                            onClick={() => openEditDialog(member)}
                          />
                          <IconButton
                            aria-label={`Delete ${member.name}`}
                            icon={Trash}
                            variant="secondary"
                            onClick={() => openDeleteDialog(member)}
                          />
                        </div>
                      </Table.Cell>
                    </Table.Row>
                  ))}
                </Table.Body>
              </Table>

              <div className="flex flex-col gap-4 border-t border-(--border-subtle-plus) px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
                <p className="text-sm text-(--text-muted)">
                  Showing {pageStart + 1}-{pageStart + visibleMembers.length} of {filteredMembers.length} members
                </p>
                <Pagination
                  currentPage={currentPage}
                  totalPages={totalPages}
                  onPageChange={(nextPage) =>
                    updateQuery({
                      page: String(nextPage),
                    })
                  }
                >
                  <Pagination.Prev />
                  <Pagination.Pages />
                  <Pagination.Next />
                </Pagination>
              </div>
            </div>
          )}
        </Tabs.Panel>

        <Tabs.Panel value="suggestions" className="flex flex-col gap-6">
          <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_auto]">
            <div className="rounded-[28px] border border-(--border-subtle-plus) bg-(--bg-base) p-5 shadow-[var(--shadow-subtle)]">
              <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <h3 className="text-lg font-semibold tracking-[-0.03em] text-(--text-primary)">
                    Suggestions queue
                  </h3>
                  <p className="mt-1 text-sm leading-6 text-(--text-muted)">
                    {viewerRole === "Moderator"
                      ? "Moderator mode stays scoped to Media suggestions so you can preview the review lane without owner-wide controls."
                      : "Owners and admins can review every department from one queue and update statuses inline."}
                  </p>
                </div>
                <Badge variant="neutral" size="md">
                  {visibleSuggestions.length} visible suggestions
                </Badge>
              </div>
            </div>

            <div className="rounded-[28px] border border-(--border-subtle-plus) bg-(--bg-base) p-5 shadow-[var(--shadow-subtle)]">
              <p className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-muted)">
                Visible to
              </p>
              <div className="mt-3 flex items-center gap-2">
                <Badge variant="brand" size="md">
                  {viewerRole}
                </Badge>
                <Badge variant="neutral" size="md">
                  {departmentFilter}
                </Badge>
              </div>
            </div>
          </div>

          <div className="overflow-x-auto">
            <div className="inline-flex min-w-full gap-2 rounded-[24px] border border-(--border-subtle-plus) bg-(--bg-base) p-2 shadow-[var(--shadow-subtle)]">
              {departmentTabs.map((department) => {
                const active = departmentFilter === department;

                return (
                  <button
                    key={department}
                    type="button"
                    className={cn(
                      "rounded-2xl px-4 py-2.5 text-sm font-medium transition-[background-color,color,box-shadow] duration-150 ease-out focus-visible:outline-none focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]",
                      active
                        ? "bg-(--color-brand) text-(--text-on-accent) shadow-[var(--shadow-btn-primary)]"
                        : "bg-(--bg-subtle) text-(--text-muted) hover:text-(--text-primary)",
                    )}
                    onClick={() =>
                      updateQuery({
                        department: department === "All" ? undefined : department,
                      })
                    }
                  >
                    {department}
                  </button>
                );
              })}
            </div>
          </div>

          {visibleSuggestions.length === 0 ? (
            <EmptyState
              title="Nothing is waiting in this review lane"
              description="Change the department scope or switch viewer roles to inspect a different part of the suggestions queue."
            />
          ) : (
            <div className="overflow-hidden rounded-[28px] border border-(--border-subtle-plus) bg-(--bg-base) shadow-[var(--shadow-subtle)]">
              <Table className="min-w-[980px]">
                <Table.Header>
                  <Table.Row className="hover:bg-transparent">
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      Suggestion
                    </Table.Head>
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      Description
                    </Table.Head>
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      Department
                    </Table.Head>
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      Status
                    </Table.Head>
                    <Table.Head className="px-5 py-4 text-[11px] uppercase tracking-[0.16em]">
                      Action
                    </Table.Head>
                  </Table.Row>
                </Table.Header>
                <Table.Body>
                  {visibleSuggestions.map((suggestion) => (
                    <Table.Row key={suggestion.id}>
                      <Table.Cell className="px-5 py-4">
                        <div className="flex min-w-0 items-start gap-3">
                          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-(--color-brand)/10 text-sm font-semibold text-(--text-accent)">
                            {getInitials(suggestion.memberName)}
                          </div>
                          <div className="min-w-0 space-y-1">
                            <div className="truncate text-sm font-semibold text-(--text-primary)">
                              {suggestion.title}
                            </div>
                            <div className="text-sm text-(--text-muted)">{suggestion.memberName}</div>
                            <div className="text-xs text-(--text-subtle)">
                              {suggestion.requester} - {formatDateTimeLabel(suggestion.createdAt)}
                            </div>
                          </div>
                        </div>
                      </Table.Cell>
                      <Table.Cell className="px-5 py-4">
                        <p className="max-w-[340px] text-sm leading-6 text-(--text-muted)">
                          {suggestion.description}
                        </p>
                      </Table.Cell>
                      <Table.Cell className="px-5 py-4">
                        <Badge variant="neutral" size="md">
                          {suggestion.department}
                        </Badge>
                      </Table.Cell>
                      <Table.Cell className="px-5 py-4">
                        <Badge variant={suggestionStatusVariants[suggestion.status]} size="md">
                          {suggestion.status}
                        </Badge>
                      </Table.Cell>
                      <Table.Cell className="px-5 py-4">
                        <label className="sr-only" htmlFor={`status-${suggestion.id}`}>
                          Change suggestion status for {suggestion.memberName}
                        </label>
                        <div className="relative max-w-[180px]">
                          <select
                            id={`status-${suggestion.id}`}
                            value={suggestion.status}
                            onChange={(event) =>
                              handleSuggestionStatusChange(
                                suggestion.id,
                                event.target.value as SuggestionStatus,
                              )
                            }
                            className="min-h-11 w-full appearance-none rounded-2xl border border-(--border-subtle) bg-(--bg-base) px-4 py-3 pr-11 text-sm font-medium text-(--text-primary) transition-[border-color,box-shadow] duration-150 ease-out focus-visible:outline-none focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]"
                          >
                            {SUGGESTION_STATUSES.map((status) => (
                              <option key={status} value={status}>
                                {status}
                              </option>
                            ))}
                          </select>
                          <CaretDown
                            size={16}
                            weight="bold"
                            aria-hidden="true"
                            className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-(--text-muted)"
                          />
                        </div>
                      </Table.Cell>
                    </Table.Row>
                  ))}
                </Table.Body>
              </Table>
            </div>
          )}
        </Tabs.Panel>
      </Tabs>

      <Dialog
        open={dialogState?.type === "create" || dialogState?.type === "edit"}
        onOpenChange={(open) => {
          if (!open) {
            closeDialog();
          }
        }}
        title={dialogState?.type === "create" ? "Create member access" : "Edit member access"}
        description={
          directMutation
            ? "Changes are applied directly after a quick verification step."
            : "Moderator mode sends this change as a suggestion for owner or admin review."
        }
        initialFocusRef={nameInputRef as React.RefObject<HTMLElement>}
        size="lg"
        footer={
          <div className="flex flex-col-reverse gap-3 sm:flex-row sm:items-center sm:justify-end">
            <Button variant="secondary" onClick={closeDialog}>
              Cancel
            </Button>
            <Button form="member-form" type="submit">
              {directMutation
                ? dialogState?.type === "create"
                  ? "Create member"
                  : "Save changes"
                : "Submit suggestion"}
            </Button>
          </div>
        }
      >
        {formState ? (
          <form id="member-form" className="space-y-5" onSubmit={handleMemberSubmit}>
            <div className="grid gap-5 lg:grid-cols-2">
              <div className="space-y-1.5">
                <label
                  htmlFor="member-name"
                  className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-muted)"
                >
                  Full name
                </label>
                <input
                  ref={nameInputRef}
                  id="member-name"
                  type="text"
                  value={formState.name}
                  onChange={(event) =>
                    setFormState({
                      ...formState,
                      name: event.target.value,
                    })
                  }
                  placeholder="Enter full name"
                  className={cn(
                    "min-h-12 w-full rounded-2xl border bg-(--bg-base) px-4 py-3 text-sm text-(--text-primary) placeholder:text-(--text-subtle) transition-[border-color,box-shadow] duration-150 ease-out focus-visible:outline-none",
                    formErrors.name
                      ? "border-(--color-destructive) focus-visible:shadow-[0_0_0_4px_var(--focus-ring-error)]"
                      : "border-(--border-subtle) focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]",
                  )}
                />
                {formErrors.name ? (
                  <p className="text-sm text-(--color-destructive)">{formErrors.name}</p>
                ) : null}
              </div>

              <div className="space-y-1.5" ref={roleMenuRef}>
                <label
                  htmlFor="member-roles"
                  className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-muted)"
                >
                  Roles
                </label>
                <button
                  id="member-roles"
                  type="button"
                  aria-expanded={roleMenuOpen}
                  aria-haspopup="listbox"
                  className={cn(
                    "flex min-h-12 w-full items-center justify-between gap-3 rounded-2xl border bg-(--bg-base) px-4 py-3 text-sm transition-[border-color,box-shadow] duration-150 ease-out focus-visible:outline-none",
                    formErrors.roles
                      ? "border-(--color-destructive) focus-visible:shadow-[0_0_0_4px_var(--focus-ring-error)]"
                      : "border-(--border-subtle) focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]",
                  )}
                  onClick={() => setRoleMenuOpen((open) => !open)}
                >
                  <div className="flex min-w-0 flex-wrap gap-1.5 text-left">
                    {formState.roles.length > 0 ? (
                      formState.roles.map((role) => (
                        <Badge key={role} variant={roleBadgeVariants[role]}>
                          {role}
                        </Badge>
                      ))
                    ) : (
                      <span className="text-(--text-subtle)">Select roles...</span>
                    )}
                  </div>
                  <CaretDown
                    size={16}
                    weight="bold"
                    aria-hidden="true"
                    className={cn(
                      "shrink-0 text-(--text-muted) transition-transform duration-150 ease-out",
                      roleMenuOpen && "rotate-180",
                    )}
                  />
                </button>

                {roleMenuOpen ? (
                  <div
                    role="listbox"
                    className="absolute z-30 mt-2 w-full rounded-[24px] border border-(--border-subtle-plus) bg-(--bg-base) p-2 shadow-[var(--shadow-subtle-active)]"
                  >
                    {MEMBER_ROLES.map((role) => {
                      const selected = formState.roles.includes(role);

                      return (
                        <button
                          key={role}
                          type="button"
                          className={cn(
                            "flex w-full items-center gap-3 rounded-2xl px-3 py-2.5 text-left text-sm transition-[background-color,color] duration-150 ease-out",
                            selected
                              ? "bg-(--color-brand)/10 text-(--text-primary)"
                              : "hover:bg-(--bg-subtle)",
                          )}
                          onClick={() => handleRoleToggle(role)}
                        >
                          <span
                            className={cn(
                              "flex h-5 w-5 items-center justify-center rounded-md border",
                              selected
                                ? "border-(--border-brand) bg-(--color-brand) text-(--text-on-accent)"
                                : "border-(--border-subtle) text-transparent",
                            )}
                          >
                            <Check size={12} weight="bold" aria-hidden="true" />
                          </span>
                          <Badge variant={roleBadgeVariants[role]}>{role}</Badge>
                        </button>
                      );
                    })}
                  </div>
                ) : null}

                {formErrors.roles ? (
                  <p className="text-sm text-(--color-destructive)">{formErrors.roles}</p>
                ) : null}
              </div>

              <div className="space-y-1.5">
                <label
                  htmlFor="member-gmail"
                  className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-muted)"
                >
                  Gmail
                </label>
                <input
                  id="member-gmail"
                  type="email"
                  value={formState.gmail}
                  onChange={(event) =>
                    setFormState({
                      ...formState,
                      gmail: event.target.value,
                    })
                  }
                  placeholder="name@team.com"
                  className={cn(
                    "min-h-12 w-full rounded-2xl border bg-(--bg-base) px-4 py-3 text-sm text-(--text-primary) placeholder:text-(--text-subtle) transition-[border-color,box-shadow] duration-150 ease-out focus-visible:outline-none",
                    formErrors.gmail
                      ? "border-(--color-destructive) focus-visible:shadow-[0_0_0_4px_var(--focus-ring-error)]"
                      : "border-(--border-subtle) focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]",
                  )}
                />
                {formErrors.gmail ? (
                  <p className="text-sm text-(--color-destructive)">{formErrors.gmail}</p>
                ) : null}
              </div>

              <div className="space-y-1.5">
                <div className="flex items-center justify-between gap-3">
                  <label
                    htmlFor="member-password"
                    className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-muted)"
                  >
                    Password
                  </label>
                  <Button
                    type="button"
                    variant="secondary"
                    size="sm"
                    onClick={() =>
                      setFormState({
                        ...formState,
                        password: generatePassword(),
                        passwordAutoGenerated: true,
                      })
                    }
                  >
                    Generate new
                  </Button>
                </div>
                <input
                  id="member-password"
                  type="text"
                  value={formState.password}
                  onChange={(event) =>
                    setFormState({
                      ...formState,
                      password: event.target.value,
                      passwordAutoGenerated: false,
                    })
                  }
                  className={cn(
                    "min-h-12 w-full rounded-2xl border bg-(--bg-base) px-4 py-3 font-mono text-sm text-(--text-primary) transition-[border-color,box-shadow] duration-150 ease-out focus-visible:outline-none",
                    formErrors.password
                      ? "border-(--color-destructive) focus-visible:shadow-[0_0_0_4px_var(--focus-ring-error)]"
                      : "border-(--border-subtle) focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]",
                  )}
                />
                {formErrors.password ? (
                  <p className="text-sm text-(--color-destructive)">{formErrors.password}</p>
                ) : formState.passwordAutoGenerated ? (
                  <p className="text-sm text-(--text-muted)">Auto-generated password ready to send.</p>
                ) : null}
              </div>
            </div>

            <div className="space-y-1.5">
              <label
                htmlFor="member-notes"
                className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-muted)"
              >
                Notes
              </label>
              <textarea
                id="member-notes"
                rows={3}
                value={formState.notes}
                onChange={(event) =>
                  setFormState({
                    ...formState,
                    notes: event.target.value,
                  })
                }
                placeholder="Optional notes about this member..."
                className="w-full rounded-2xl border border-(--border-subtle) bg-(--bg-base) px-4 py-3 text-sm text-(--text-primary) placeholder:text-(--text-subtle) transition-[border-color,box-shadow] duration-150 ease-out focus-visible:outline-none focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]"
              />
            </div>

            {directMutation ? (
              <div className="rounded-[24px] border border-(--border-subtle-plus) bg-(--bg-subtle) p-4">
                <p className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-muted)">
                  Verification - solve to confirm
                </p>
                <div className="mt-3 flex items-center gap-3">
                  <span className="text-base font-semibold text-(--text-primary) [font-variant-numeric:tabular-nums]">
                    {verificationChallenge.left} + {verificationChallenge.right} =
                  </span>
                  <input
                    type="number"
                    value={formState.verificationAnswer}
                    onChange={(event) =>
                      setFormState({
                        ...formState,
                        verificationAnswer: event.target.value,
                      })
                    }
                    className={cn(
                      "min-h-11 w-24 rounded-2xl border bg-(--bg-base) px-3 py-2 text-center text-sm font-semibold text-(--text-primary) transition-[border-color,box-shadow] duration-150 ease-out focus-visible:outline-none",
                      formErrors.verification
                        ? "border-(--color-destructive) focus-visible:shadow-[0_0_0_4px_var(--focus-ring-error)]"
                        : "border-(--border-subtle) focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]",
                    )}
                  />
                </div>
                {formErrors.verification ? (
                  <p className="mt-2 text-sm text-(--color-destructive)">
                    {formErrors.verification}
                  </p>
                ) : null}
              </div>
            ) : (
              <div className="rounded-[24px] border border-(--status-info-border) bg-(--status-info-bg) p-4 text-sm leading-6 text-(--color-info)">
                Moderator mode does not apply changes directly. Submitting this form creates a review suggestion instead.
              </div>
            )}
          </form>
        ) : null}
      </Dialog>

      <Dialog
        open={dialogState?.type === "delete" && currentMember !== null}
        onOpenChange={(open) => {
          if (!open) {
            closeDialog();
          }
        }}
        title={directMutation ? "Delete member" : "Suggest member deletion"}
        description={
          directMutation
            ? "This action cannot be undone. Confirm the member details below before deleting."
            : "This will be sent to the review queue so an owner or admin can approve it."
        }
        size="md"
        footer={
          <div className="flex flex-col-reverse gap-3 sm:flex-row sm:items-center sm:justify-end">
            <Button variant="secondary" onClick={closeDialog}>
              Cancel
            </Button>
            <button
              type="button"
              onClick={handleDeleteConfirm}
              className={cn(
                "inline-flex min-h-[45px] items-center justify-center rounded-lg px-4 text-sm font-semibold text-(--text-on-accent) transition-[background-color,box-shadow,transform] duration-150 ease-out focus-visible:outline-none",
                directMutation
                  ? "bg-(--color-destructive) shadow-[var(--shadow-subtle)] focus-visible:shadow-[0_0_0_4px_var(--focus-ring-error)] hover:brightness-95 active:scale-[0.97]"
                  : "bg-(--color-brand) shadow-[var(--shadow-btn-primary)] focus-visible:shadow-[var(--shadow-btn-primary),0_0_0_4px_var(--focus-ring)] hover:brightness-95 active:scale-[0.97]",
              )}
            >
              {directMutation ? "Delete member" : "Submit suggestion"}
            </button>
          </div>
        }
      >
        {currentMember ? (
          <div className="space-y-5">
            <div className="flex items-center gap-3 rounded-[24px] border border-(--border-subtle-plus) bg-(--bg-subtle) p-4">
              <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-(--color-brand)/10 text-sm font-semibold text-(--text-accent)">
                {getInitials(currentMember.name)}
              </div>
              <div className="min-w-0">
                <div className="truncate text-sm font-semibold text-(--text-primary)">
                  {currentMember.name}
                </div>
                <div className="mt-1 flex flex-wrap gap-1.5">
                  {currentMember.roles.map((role) => (
                    <Badge key={role} variant={roleBadgeVariants[role]}>
                      {role}
                    </Badge>
                  ))}
                </div>
              </div>
            </div>

            <div className="grid gap-3 rounded-[24px] border border-(--border-subtle-plus) bg-(--bg-subtle) p-4 text-sm text-(--text-muted) sm:grid-cols-2">
              <div>
                <div className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-subtle)">
                  Member ID
                </div>
                <div className="mt-1 text-(--text-primary)">{currentMember.id}</div>
              </div>
              <div>
                <div className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-subtle)">
                  Department
                </div>
                <div className="mt-1 text-(--text-primary)">{currentMember.department}</div>
              </div>
            </div>

            {directMutation ? (
              <div className="rounded-[24px] border border-(--border-subtle-plus) bg-(--bg-subtle) p-4">
                <p className="text-xs font-semibold uppercase tracking-[0.16em] text-(--text-muted)">
                  Verification - solve to confirm
                </p>
                <div className="mt-3 flex items-center gap-3">
                  <span className="text-base font-semibold text-(--text-primary) [font-variant-numeric:tabular-nums]">
                    {verificationChallenge.left} + {verificationChallenge.right} =
                  </span>
                  <input
                    type="number"
                    value={formState?.verificationAnswer ?? ""}
                    onChange={(event) =>
                      setFormState({
                        name: "",
                        roles: [],
                        gmail: "",
                        password: "",
                        notes: "",
                        passwordAutoGenerated: false,
                        verificationAnswer: event.target.value,
                      })
                    }
                    className={cn(
                      "min-h-11 w-24 rounded-2xl border bg-(--bg-base) px-3 py-2 text-center text-sm font-semibold text-(--text-primary) transition-[border-color,box-shadow] duration-150 ease-out focus-visible:outline-none",
                      formErrors.verification
                        ? "border-(--color-destructive) focus-visible:shadow-[0_0_0_4px_var(--focus-ring-error)]"
                        : "border-(--border-subtle) focus-visible:shadow-[0_0_0_4px_var(--focus-ring)]",
                    )}
                  />
                </div>
                {formErrors.verification ? (
                  <p className="mt-2 text-sm text-(--color-destructive)">
                    {formErrors.verification}
                  </p>
                ) : null}
              </div>
            ) : (
              <div className="rounded-[24px] border border-(--status-info-border) bg-(--status-info-bg) p-4 text-sm leading-6 text-(--color-info)">
                Moderator mode sends deletes into review instead of removing the member immediately.
              </div>
            )}
          </div>
        ) : null}
      </Dialog>
    </section>
  );
}
